package:
  name: esgfpid
  version: 0.8.1

source:
  git_rev: ska-rel
  git_url: https://github.com/sashakames/esgf-pid

build:
  number: 0
  noarch: python
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - configparser
    - pika
    - requests

test:
  commands:
    - python -c "import esgfpid"

about:
  home:	https://github.com/IS-ENES-Data/esgf-pid
  summary: ESGF PID Module
  license: BSD
  license_file: LICENSE

