package:
  name: esgfpid
  version: 0.8.0

source:
  git_rev: ska-rel
  git_url: https://github.com/sashakames/esgf-pid

build:
  number: 0
  noarch: python
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - configparser
    - pika

test:
  commands:
    - python -c "import esgfpid"

about:
  home: http://github.com/ESGF/esgf-config-parser
  summary: ESGF Configuration Parser
  license: BSD
  license_file: LICENSE

